version: '3.4'

services:
  # reverseproxy:
  #   container_name: nginxgateway
  #   restart: always
  #   depends_on:
  #     - identityserver
  #     - catalog.api
  #     - basket.api
  #     - discount.api
  #     - ordering.api
  #   ports:
  #     - '44344:44344'

  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - '6379:6379'

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  orderdb:
    container_name: orderdb
    hostname: orderdb
    environment:
      MSSQL_SA_PASSWORD: 'Admin1234'
      MSSQL_PID: 'Developer'
      ACCEPT_EULA: 'Y'
    restart: always
    ports:
      - '1433:1433'

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:80
      - 'DatabaseSettings:ConnectionString=mongodb://catalogdb:27017'
      - 'DatabaseSettings__DatabaseName=CatalogDb'
      - 'DatabaseSettings__CollectionName=Products'
      - 'DatabaseSettings__BrandsCollection=Brands'
      - 'DatabaseSettings__TypesCollection=Types'
      - 'ElasticConfiguration__Uri=http://elasticsearch:9200'
    depends_on:
      - catalogdb
    ports:
      - '9000:80'

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:80
      - 'CacheSettings__ConnectionString=basketdb:6379'
      - 'GrpcSettings__DiscountUrl=http://discount.api'
      - 'EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672'
      - 'ElasticConfiguration__Uri=http://elasticsearch:9200'
    depends_on:
      - basketdb
      - rabbitmq
    ports:
      - '9001:80'

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:80
      - 'DatabaseSettings__ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;'
      - 'ElasticConfiguration__Uri=http://elasticsearch:9200'
    depends_on:
      - discountdb
    ports:
      - '9002:80'

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:80
      - 'ConnectionStrings__OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=Admin1234;TrustServerCertificate=true;MultipleActiveResultSets=true'
      - 'EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672'
      - 'ElasticConfiguration__Uri=http://elasticsearch:9200'
    depends_on:
      - orderdb
      - rabbitmq
    ports:
      - '9003:80'

  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:80
      - 'ElasticConfiguration__Uri=http://elasticsearch:9200'
    depends_on:
      #      - identityserver
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api
    ports:
      - '9010:80'

  elasticsearch:
    container_name: elasticsearch
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - discovery.type=single-node
    ports:
      - '9200:9200'
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - '5601:5601'

  # identityserver:
  #   container_name: identityserver
  #   hostname: identityserver
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=https://*:9099;http://*:9009
  #     - ASPNETCORE_HTTP_PORT=9009
  #     - ASPNETCORE_HTTPS_PORT=9099
  #     - ASPNETCORE_Kestrel__Certificates__Default__Password=Beherenow_Beginnersm3nd
  #     - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/localhost.pfx
  #     - 'ElasticConfiguration__Uri=http://elasticsearch:9200'
  #   ports:
  #     - '9009:9009'
  #     - '9099:9099'
  #   volumes:
  #     - ./LocalhostCertificate:/https:ro
